# Generated by Django 5.0.4 on 2024-04-11 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_product_created_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="created_at", new_name="product_timestamp",
        ),
        migrations.RemoveField(model_name="product", name="updated_at",),
        migrations.RemoveField(model_name="store", name="created_at",),
        migrations.RemoveField(model_name="store", name="updated_at",),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.IntegerField(unique=True)),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "transaction_time",
                    models.TimeField(default=django.utils.timezone.now),
                ),
                ("transaction_qty", models.IntegerField()),
                ("unit_price", models.IntegerField()),
                ("product_category", models.CharField(max_length=100)),
                ("product_detail", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.store"
                    ),
                ),
            ],
        ),
    ]
